#pragma once

// GENERATED by Vibe-Reverse-Engineering/patches/AssassinsCreed/scripts/specular/gen_table.py from
// dumps/specular/census.json (colour-pass PS of frame_capture_01, data-flow traced by analyze.py) - do not
// edit. Key: FNV-1a 64 of the PS bytecode. Every engine specular lobe is Phong:
// pow(sat(dot(reflect(-L, N), V)), n) * intensity, added to the diffuse sum (docs/notes/specular.md).

#include <cstdint>

namespace ac1rtx::specular_table {

enum class Exponent : uint8_t { kNone, kConstant, kTexturePlusConstant, kTextureTimesK };

struct Entry {
  uint64_t bytecodeHash;
  Exponent mode;
  uint8_t sampler;      // texture modes: sampler register
  uint8_t channel;      // texture modes: 0..3 = r g b a
  uint16_t constReg;    // constant modes: PS float register
  uint8_t constComp;    // component of that register
  float k;              // kTextureTimesK factor
  const char* name;     // md5[:8] of the disasm (dumps/specular/ps_<name>.txt)
};

inline constexpr Entry kEntries[] = {
  { 0xABDCAD40E1CA0E5Full, Exponent::kNone, 0, 0, 0, 0, 0.0f, "eceb2d0b" },  // 566 draws
  { 0xA11B58A241FBB110ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "e56794d5" },  // 149 draws
  { 0xE7C27E3E0B52A404ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "d11e037c" },  // 94 draws
  { 0xA8238DD6A74E9DC7ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "7a87be5e" },  // 92 draws
  { 0x11516EE465C4810Dull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "9b85bc21" },  // 74 draws
  { 0xB8F5B0DA62C2CBD4ull, Exponent::kTextureTimesK, 5, 1, 0, 0, 5.0f, "b1b370c7" },  // 69 draws
  { 0xD71C8CD28DD3FB6Cull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "3acce3d4" },  // 61 draws
  { 0x6818D179A16A7B92ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "fe8e8298" },  // 60 draws
  { 0xF9C9644F2F18C8EDull, Exponent::kTextureTimesK, 4, 1, 0, 0, 10.0f, "7fd02edd" },  // 43 draws
  { 0x52FCDEB0C7D03EA3ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "a8a8a446" },  // 35 draws
  { 0xEDE9236F91C6F45Eull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "8e51fc79" },  // 33 draws
  { 0xC2AD40C1FEC9AF9Dull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "ef891748" },  // 31 draws
  { 0x0213170FD246A994ull, Exponent::kTexturePlusConstant, 6, 2, 134, 0, 0.0f, "d847d387" },  // 24 draws
  { 0x7A4A09148D477B6Cull, Exponent::kTexturePlusConstant, 6, 2, 132, 0, 0.0f, "c83dd075" },  // 22 draws
  { 0x33CCF80DD8012D1Dull, Exponent::kTexturePlusConstant, 3, 2, 132, 0, 0.0f, "ec408913" },  // 20 draws
  { 0x46824F928E2D3BA3ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "e4687ad1" },  // 20 draws
  { 0x078646B41C28BBB3ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "e11bd5f6" },  // 19 draws
  { 0x1B23281E0224BF73ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "15230681" },  // 19 draws
  { 0x33D3A8375B757B9Dull, Exponent::kTexturePlusConstant, 3, 2, 132, 0, 0.0f, "466478d4" },  // 12 draws
  { 0xA0605D13E2AA8B07ull, Exponent::kTexturePlusConstant, 3, 2, 132, 0, 0.0f, "c7b086de" },  // 11 draws
  { 0x3195A0D964910FB7ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "fb6f164e" },  // 9 draws
  { 0x1C57675BFDC3DC98ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "c771f4c5" },  // 9 draws
  { 0x5352C7E6A9B1C5AFull, Exponent::kTextureTimesK, 5, 1, 0, 0, 5.0f, "74673c36" },  // 8 draws
  { 0x9F0C1F5773CB3C0Cull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "764c4858" },  // 8 draws
  { 0x4AF87D9D667BB3A3ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "e0b22c67" },  // 7 draws
  { 0x21FFDAAE04A2772Cull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "1d96ce54" },  // 6 draws
  { 0x244F30A9E0F80F38ull, Exponent::kTexturePlusConstant, 4, 2, 131, 0, 0.0f, "554bde55" },  // 5 draws
  { 0xF99C31C234021354ull, Exponent::kConstant, 0, 0, 132, 0, 0.0f, "e7f64a98" },  // 5 draws
  { 0x67D4EC28601E140Cull, Exponent::kTexturePlusConstant, 3, 2, 132, 0, 0.0f, "07067896" },  // 4 draws
  { 0xDC351A4343B56BDEull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "62748094" },  // 4 draws
  { 0x07FCEAD05264B8FEull, Exponent::kTexturePlusConstant, 3, 2, 130, 0, 0.0f, "6fb31593" },  // 2 draws
  { 0xE568E4AE34C5F21Full, Exponent::kTexturePlusConstant, 3, 2, 130, 0, 0.0f, "5491ee99" },  // 2 draws
  { 0x302B1E32DB7E2686ull, Exponent::kTexturePlusConstant, 4, 2, 131, 0, 0.0f, "954f8f56" },  // 1 draws
  { 0xF234F2EE3F098FD9ull, Exponent::kConstant, 0, 0, 129, 0, 0.0f, "f5089a0a" },  // 1 draws
  { 0xA1BE8DE0AA3BD09Cull, Exponent::kTexturePlusConstant, 3, 2, 130, 0, 0.0f, "8fb55621" },  // 1 draws
  { 0x2A9E0AEFC507B2B1ull, Exponent::kConstant, 0, 0, 131, 0, 0.0f, "4b10e484" },  // 1 draws
  { 0x457DD9ACEA97596Aull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "e119d051" },  // 1 draws
  { 0x2F20941DD48C70FBull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "9c7f099f" },  // 1 draws
  { 0x71A518A9852BA9A5ull, Exponent::kTexturePlusConstant, 3, 2, 132, 0, 0.0f, "af0c8766" },  // 1 draws
  { 0xAAC5D7B1F8A5F735ull, Exponent::kConstant, 0, 0, 139, 0, 0.0f, "874b3319" },  // 1 draws
  { 0x088FC25C1488BAC8ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "088fc25c" },  // 0 draws
  { 0x09360A60BB4A8616ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "09360a60" },  // 0 draws
  { 0x0E0234C3BFCBED4Eull, Exponent::kConstant, 0, 0, 131, 0, 0.0f, "0e0234c3" },  // 0 draws
  { 0x1143A4FB62C0DE64ull, Exponent::kTexturePlusConstant, 3, 2, 132, 0, 0.0f, "1143a4fb" },  // 0 draws
  { 0x149CFC7399EA915Full, Exponent::kConstant, 0, 0, 135, 0, 0.0f, "149cfc73" },  // 0 draws
  { 0x1626A245C4E8B1D1ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "1626a245" },  // 0 draws
  { 0x1C4B68A10308EA91ull, Exponent::kConstant, 0, 0, 131, 0, 0.0f, "1c4b68a1" },  // 0 draws
  { 0x1CB3AA2F99FC3978ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "1cb3aa2f" },  // 0 draws
  { 0x1F4B253B3B8AE369ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "1f4b253b" },  // 0 draws
  { 0x21720CAD89FD54B5ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "21720cad" },  // 0 draws
  { 0x229E9E7BCABF8BE7ull, Exponent::kTexturePlusConstant, 3, 2, 130, 0, 0.0f, "229e9e7b" },  // 0 draws
  { 0x233D0E9A261BCD30ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "233d0e9a" },  // 0 draws
  { 0x234EA27C6B6D50FFull, Exponent::kConstant, 0, 0, 131, 0, 0.0f, "234ea27c" },  // 0 draws
  { 0x26FDE359B7DE5289ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "26fde359" },  // 0 draws
  { 0x26FF80FBD23305C9ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "26ff80fb" },  // 0 draws
  { 0x28E1CCDDDC34E43Eull, Exponent::kConstant, 0, 0, 135, 0, 0.0f, "28e1ccdd" },  // 0 draws
  { 0x294EAEA44E700374ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "294eaea4" },  // 0 draws
  { 0x2A27DA86FC4461CEull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "2a27da86" },  // 0 draws
  { 0x34946867A05CB5F8ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "34946867" },  // 0 draws
  { 0x36A729ED3BAFCBC1ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "36a729ed" },  // 0 draws
  { 0x39193F22185EA7C2ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "39193f22" },  // 0 draws
  { 0x3B272F4B7AD4B570ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "3b272f4b" },  // 0 draws
  { 0x3BC141C8F719D472ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "3bc141c8" },  // 0 draws
  { 0x3EAD5C929F41DFF0ull, Exponent::kTextureTimesK, 4, 1, 0, 0, 10.0f, "3ead5c92" },  // 0 draws
  { 0x429629C6918783BEull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "429629c6" },  // 0 draws
  { 0x447118CA0F9D3DE0ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "447118ca" },  // 0 draws
  { 0x4581B6945360D5D2ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "4581b694" },  // 0 draws
  { 0x471EC53EB112F15Cull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "471ec53e" },  // 0 draws
  { 0x4D8BCF709BCD32B7ull, Exponent::kConstant, 0, 0, 131, 0, 0.0f, "4d8bcf70" },  // 0 draws
  { 0x52A973BED8FB2FF6ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "52a973be" },  // 0 draws
  { 0x54476CB66F17A29Dull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "54476cb6" },  // 0 draws
  { 0x604A58BEF046C415ull, Exponent::kConstant, 0, 0, 131, 0, 0.0f, "604a58be" },  // 0 draws
  { 0x63C3CB739A5554ACull, Exponent::kConstant, 0, 0, 135, 0, 0.0f, "63c3cb73" },  // 0 draws
  { 0x6447A7598286F112ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "6447a759" },  // 0 draws
  { 0x6738ED3D27F2A391ull, Exponent::kConstant, 0, 0, 130, 0, 0.0f, "6738ed3d" },  // 0 draws
  { 0x6963AC92EE24F56Eull, Exponent::kTexturePlusConstant, 6, 2, 134, 0, 0.0f, "6963ac92" },  // 0 draws
  { 0x6DC8456709D9F661ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "6dc84567" },  // 0 draws
  { 0x72A781B0AB816ADEull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "72a781b0" },  // 0 draws
  { 0x73010E7676B12085ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "73010e76" },  // 0 draws
  { 0x73397B63A98060E8ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "73397b63" },  // 0 draws
  { 0x75AB3DFE450FE27Eull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "75ab3dfe" },  // 0 draws
  { 0x76F7F1A1E7305A40ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "76f7f1a1" },  // 0 draws
  { 0x783D21E150F883F6ull, Exponent::kTextureTimesK, 4, 1, 0, 0, 10.0f, "783d21e1" },  // 0 draws
  { 0x785DA922DC5673BBull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "785da922" },  // 0 draws
  { 0x7BA88B465A34FC0Bull, Exponent::kConstant, 0, 0, 131, 0, 0.0f, "7ba88b46" },  // 0 draws
  { 0x7C570F1B5FB3EEE6ull, Exponent::kConstant, 0, 0, 131, 0, 0.0f, "7c570f1b" },  // 0 draws
  { 0x7F63079B361A81D8ull, Exponent::kConstant, 0, 0, 131, 0, 0.0f, "7f63079b" },  // 0 draws
  { 0x81ED015A85717588ull, Exponent::kTexturePlusConstant, 7, 2, 134, 0, 0.0f, "81ed015a" },  // 0 draws
  { 0x853767DF0C30726Eull, Exponent::kConstant, 0, 0, 130, 0, 0.0f, "853767df" },  // 0 draws
  { 0x85C61C5E230ED8C9ull, Exponent::kConstant, 0, 0, 130, 0, 0.0f, "85c61c5e" },  // 0 draws
  { 0x8756360A031ACAB3ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "8756360a" },  // 0 draws
  { 0x877B7130605BAD37ull, Exponent::kConstant, 0, 0, 129, 0, 0.0f, "877b7130" },  // 0 draws
  { 0x88DB95F458439118ull, Exponent::kConstant, 0, 0, 131, 0, 0.0f, "88db95f4" },  // 0 draws
  { 0x8A69E15A18EC17DAull, Exponent::kTexturePlusConstant, 7, 2, 134, 0, 0.0f, "8a69e15a" },  // 0 draws
  { 0x908D198B3DC3842Bull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "908d198b" },  // 0 draws
  { 0x90C6A931CC05DD05ull, Exponent::kTexturePlusConstant, 3, 2, 130, 0, 0.0f, "90c6a931" },  // 0 draws
  { 0x92E7071E7E235F77ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "92e7071e" },  // 0 draws
  { 0x99D8700C918B24CDull, Exponent::kConstant, 0, 0, 129, 0, 0.0f, "99d8700c" },  // 0 draws
  { 0xA05BF2319D6BB2D7ull, Exponent::kTexturePlusConstant, 3, 2, 132, 0, 0.0f, "a05bf231" },  // 0 draws
  { 0xA0E398FFE37AE8E4ull, Exponent::kConstant, 0, 0, 131, 0, 0.0f, "a0e398ff" },  // 0 draws
  { 0xA2CA2175F22BF9F4ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "a2ca2175" },  // 0 draws
  { 0xA4B1908C3F5B9251ull, Exponent::kConstant, 0, 0, 131, 0, 0.0f, "a4b1908c" },  // 0 draws
  { 0xAE8DBBFB41B23518ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "ae8dbbfb" },  // 0 draws
  { 0xB01E82CFD6390C3Full, Exponent::kTextureTimesK, 5, 1, 0, 0, 5.0f, "b01e82cf" },  // 0 draws
  { 0xB83531EDD61B68F4ull, Exponent::kConstant, 0, 0, 131, 0, 0.0f, "b83531ed" },  // 0 draws
  { 0xBAE75A5DEC02793Cull, Exponent::kTexturePlusConstant, 6, 2, 132, 0, 0.0f, "bae75a5d" },  // 0 draws
  { 0xBE06822EE3111706ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "be06822e" },  // 0 draws
  { 0xC19C03252BB48F38ull, Exponent::kConstant, 0, 0, 130, 0, 0.0f, "c19c0325" },  // 0 draws
  { 0xC43AB62CC8BDAC82ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "c43ab62c" },  // 0 draws
  { 0xC6FCBD105061C3E7ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "c6fcbd10" },  // 0 draws
  { 0xCBF9E49098316426ull, Exponent::kConstant, 0, 0, 135, 0, 0.0f, "cbf9e490" },  // 0 draws
  { 0xCE72A941331C006Full, Exponent::kNone, 0, 0, 0, 0, 0.0f, "ce72a941" },  // 0 draws
  { 0xCE8C9F4BC489E10Bull, Exponent::kConstant, 0, 0, 129, 0, 0.0f, "ce8c9f4b" },  // 0 draws
  { 0xD3684DC699AB3559ull, Exponent::kConstant, 0, 0, 131, 0, 0.0f, "d3684dc6" },  // 0 draws
  { 0xD5646358C9739030ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "d5646358" },  // 0 draws
  { 0xD57C9232AAC605B8ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "d57c9232" },  // 0 draws
  { 0xD8113653BDEBE44Full, Exponent::kNone, 0, 0, 0, 0, 0.0f, "d8113653" },  // 0 draws
  { 0xDA5FEB298889A71Bull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "da5feb29" },  // 0 draws
  { 0xDC9B68B70185EEDAull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "dc9b68b7" },  // 0 draws
  { 0xDDFCD3F5233CBA2Cull, Exponent::kConstant, 0, 0, 135, 0, 0.0f, "ddfcd3f5" },  // 0 draws
  { 0xDE0BD13C73A510C7ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "de0bd13c" },  // 0 draws
  { 0xE070F0861EE94541ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "e070f086" },  // 0 draws
  { 0xE0F0CE3434064CCDull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "e0f0ce34" },  // 0 draws
  { 0xE8442E03BDBC6751ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "e8442e03" },  // 0 draws
  { 0xEBAE7C64C0668611ull, Exponent::kConstant, 0, 0, 131, 0, 0.0f, "ebae7c64" },  // 0 draws
  { 0xEBD9C2D882171DC7ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "ebd9c2d8" },  // 0 draws
  { 0xEC3864B69C439280ull, Exponent::kConstant, 0, 0, 135, 0, 0.0f, "ec3864b6" },  // 0 draws
  { 0xEE2DACCEF91AAA1Bull, Exponent::kConstant, 0, 0, 129, 0, 0.0f, "ee2dacce" },  // 0 draws
  { 0xEEF09AA5AF65160Eull, Exponent::kConstant, 0, 0, 130, 0, 0.0f, "eef09aa5" },  // 0 draws
  { 0xFC750BAFDCAAF4EBull, Exponent::kTextureTimesK, 5, 1, 0, 0, 5.0f, "fc750baf" },  // 0 draws
  { 0xFDB8A908AC204627ull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "fdb8a908" },  // 0 draws
  { 0xFE762CB0F2D5D5EBull, Exponent::kNone, 0, 0, 0, 0, 0.0f, "fe762cb0" },  // 0 draws
};

}  // namespace ac1rtx::specular_table
