rtx.useWhiteMaterialMode = False
rtx.atmosphere.cloudEnabled = True
rtx.atmosphere.sunRotation = 150
rtx.atmosphere.timeCycleEnable = False
rtx.atmosphere.cloudColor = 0.904899, 0.855644, 0.753648
rtx.atmosphere.planetRadius = 6371
rtx.useVertexCapture = False
rtx.atmosphere.aerosolDensity = 1.1
rtx.atmosphere.rayleighScattering = 0.0136931, 0.0157279, 0.022519
rtx.atmosphere.sunElevation = 37.9999
rtx.atmosphere.mieScattering = 0.00351233, 0.00340403, 0.0027127
rtx.debugView.debugViewIdx = 0
rtx.antiCulling.object.enable = True
rtx.atmosphere.ozoneAbsorption = 0.00065, 0.001881, 8.5e-05
rtx.pointInstancer.enable = False
rtx.antiCulling.object.enableHighPrecisionAntiCulling = True
rtx.atmosphere.mieAbsorption = 0.00399424, 0.00391595, 0.00353381
rtx.atmosphere.ozoneLayerAltitude = 25
rtx.zUp = True
rtx.atmosphere.sunIntensity = 0.3
rtx.atmosphere.airDensity = 1
rtx.atmosphere.cloudDensity = 2
rtx.postfx.enableMotionBlurEmissive = True
rtx.atmosphere.aerialPerspectiveSceneShadow = False
rtx.skyMode = 1
rtx.atmosphere.aerialPerspective = True
rtx.atmosphere.ozoneLayerWidth = 15
rtx.atmosphere.cloudCoverageMean = 0.05
rtx.enableApiInjectionMarker = True
rtx.atmosphere.ozoneDensity = 1
rtx.atmosphere.atmosphereThickness = 100
rtx.antiCulling.object.enableInfinityFarFrustum = True
rtx.enableRaytracing = True
rtx.atmosphere.mieAnisotropy = 0.8
rtx.atmosphere.sunIlluminance = 19.2507, 19.0381, 17.1426
rtx.horizonFog.enable = True
rtx.horizonFog.density = 0.0008
rtx.horizonFog.startMeters = 40
rtx.horizonFog.heightFalloff = 0.004
rtx.horizonFog.maxOpacity = 0.75
rtx.horizonFog.desaturation = 0.25
